name: Python Binary Packages

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-linux-wheels:
    name: Build Linux Python Wheels (+PGO)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download dictionary
        run: bash fetch_dictionary.sh

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: eiennohito/gha-manylinux-build@master
        with:
          script: python/build-wheels-manylinux-pgo.sh

      - uses: actions/upload-artifact@v2
        with:
          path: python/dist/*manylinux*

  build-non-linux-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install cibuildwheel
        run: |
          python -m pip install -U pip
          python -m pip install cibuildwheel==2.2.0b1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse python
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl