name: Deploy Documentation

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Build rust document
        # build document of lib only for now to avoid name collision.
        working-directory: ./sudachi
        run:
          cargo doc --no-deps
      - name: Move docs
        run: mv ./target/doc ./docs/rust

      - name: Setup python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.11'
      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
      - name: Install dependencies
        run: uv pip install --system -U sphinx sphinx-rtd-theme

      - name: Build python binding
        run: uv pip install --system .

      - name: Build pyhton document
        working-directory: ./python/docs
        run: make html
      - name: Move docs
        run: mv ./python/docs/build/html ./docs/python

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
