name: Python Release

on:
  push:
    tags:
      - python-v*

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: python3 -m pip install -U setuptools setuptools-rust

      - name: Build
        working-directory: ./python
        run: bash build-sdist.sh


  upload-package:
    name: Upload package to PyPi
    runs-on: Ubuntu-latest
    needs: [build-sdist]
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Upload to PyPi
        working-directory: ./python
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run:
          twine upload dist/* 


