name: Python Source Package (Common)

on:
  push:
    tags:
      - v*

jobs:
  upload-sdist:
    name: Build and upload source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools setuptools-rust twine

      - name: Build
        working-directory: ./python
        run: bash build-sdist.sh

      - name: Upload to PyPi
        working-directory: ./python
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run:
          twine upload dist/*
