name: Rust-Non-Cached

on:
  schedule:
    - cron: '0 18 * * *' # run at 18:00 UTC (JST 03:00)

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Download dictionary
        run: bash fetch_dictionary.sh
      - name: Run tests (Debug)
        run: cargo test --verbose
      - name: Run tests (Release)
        run: cargo test --verbose
