name: Rust-Non-Cached

on:
  schedule:
    - cron: '0 18 * * *' # run at 18:00 UTC (JST 03:00)

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6.0.2
    - name: Download dictionary
      run: bash fetch_dictionary.sh "20220519" "core" "8de60382bde6b8307a10daa265569164a6296b28d52d793c3ed0757786969365"
    - name: Run tests (Debug)
      run: cargo test --verbose
    - name: Run tests (Release)
      run: cargo test --release --verbose
