name: Lint-Rustfmt

on:
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Rustfmt
        run: cargo fmt -- --check --files-with-diff